### ISSUE TITLE
implement automated build

### ISSUE THREAD

**Issue by azhozhin** [azhozhin/html-proofer.js#1]

**Comment by azhozhin** [comment]
base image - node:16
we can try alpine first

**Comment by saadparwaiz1** [comment]
Hi there, I can see the CI is already done? What do you want to do more with it? I can have a look

**Comment by azhozhin** [comment]
I would like to have build + test (with coverage).
Test results as well as coverage should be visible somehow, it is hard to dig in actions logs to find out how many tests are broken

**Comment by azhozhin** [comment]
implemented build + test + coverage
